python -m lerobot.async_inference.robot_client \
    --server_address=127.0.0.1:8080 \
    --robot.type=agilex_cobot \
    --policy_type=pi05 \
    --pretrained_name_or_path=/home/xlk/work/lerobot/checkpoints/fold_towel/030000/pretrained_model \
    --policy_device=cuda \
    --actions_per_chunk=50 \
    --chunk_size_threshold=0.5 \
    --fps=50 \
    --aggregate_fn_name=latest_only \
    --debug_visualize_queue_size=true \
    --task="Carefully fold the towel and then place the folded towel on the black notebook" \